# SPDX-License-Identifier: GPL-2.0
#
# Makefile for linux/drivers/platform
#

obj-$(CONFIG_X86)		+= x86/
obj-$(CONFIG_MIPS)		+= mips/
obj-$(CONFIG_OLPC)		+= olpc/
obj-$(CONFIG_GOLDFISH)		+= goldfish/
obj-$(CONFIG_CHROME_PLATFORMS)	+= chrome/
# A.Kamal Add Renesas VCFPGA PCI support
obj-$(CONFIG_RENESAS_VCFPGA_PLATFORM)	+= renesas/vcfpga/
# A.Kamal Add Renesas VCFPGA PCI support
