# A.Kamal (VC2FPGA)
#
# Makefile for the Renesas R-SWITCH  FPGA Debug device.
#
#AK: Suppress GCC 4.9 warning for date & time 
EXTRA_CFLAGS +=-Wno-date-time
obj-$(CONFIG_RENESAS_VCFPGA_PLATFORM) += vcfpga.o
rswitc2h_core-objs := vcfpga.o
# A.Kamal (VC2FPGA)

